### ISSUE TITLE
PPO learning rate annealing 

### ISSUE THREAD

**Issue by epicgamer17** [epicgamer17/rl-research#17]

**Comment by Usernamealready-taken** [comment]
Doesn't Adam already have built in annealing ?
On the paper : "Depending on the task, the implementation sometimes anneals the learning rate of Adam (Kingma & Ba, 2014) (an already adaptive method) for optimizatio" => it doesn't seem like it is used much

**Comment by Usernamealready-taken** [comment]
done by epicgamer17
